name: Cypress Tests

on: push

env:
  VITE_API_URL: http://localhost:3001
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout c贸digo
        uses: actions/checkout@v3

      - name:  Instalar depend锚ncias e build
        uses: cypress-io/github-action@v5
        with:
          runTests: false
          build: npm run build

      - name:  Salvar pastas de build como artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-folders
          if-no-files-found: error
          path: |
            client/dist
            server/dist

  end-to-end-tests:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6]
    steps:
      - name:  Checkout c贸digo
        uses: actions/checkout@v3

      - name:  Baixar as pastas de build
        uses: actions/download-artifact@v4
        with:
          name: build-folders

      - name: И Rodar testes E2E
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:ci
          wait-on: 'http://localhost:3000, http://localhost:3001/heroes'
          command: npm run test:e2e:ci

  component-tests:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6]
    steps:
      - name:  Checkout c贸digo
        uses: actions/checkout@v3

      - name:  Baixar as pastas de build
        uses: actions/download-artifact@v4
        with:
          name: build-folders

      - name: И Rodar Component Tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:ct:ci

  api-tests:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6]
    steps:
      - name:  Checkout c贸digo
        uses: actions/checkout@v3

      - name:  Baixar as pastas de build
        uses: actions/download-artifact@v4
        with:
          name: build-folders

      - name: И Rodar API Tests
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:ci
          wait-on: 'http://localhost:3000, http://localhost:3001/heroes'
          command: npm run test:api:ci
